name: Build and deploy PHP app to Azure Web App - atharaman-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

# THIS BLOCK IS CRITICAL - DO NOT REMOVE
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, mysql

      - name: Install dependencies
        run: composer install --ignore-platform-reqs --optimize-autoloader --no-dev

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_280E70FFBCB406783F3A8A283877CA8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3B4F4D34131142B297849B87AAF139CA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_168D44FC9641429EA167F73134ACB71B }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'atharaman-api'
          package: .
          # This forces Azure to recognize the public folder
          startup-script: 'cp /home/site/wwwroot/public/index.php /home/site/wwwroot/index.php && apache2-foreground'
